global:
  scrape_interval: 5s

scrape_configs:

  # Метрики с локальной машины (контейнера)
  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  # Kafka — через kafka_exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
    metrics_path: /metrics

  - job_name: 'event-collector'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'events-collector-service:9991' ]

  - job_name: 'device-collector'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'device-collector-service:9992' ]

  - job_name: 'device'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'device-service:9993' ]

  #Метрики контейнеров
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cadvisor:8080' ]


